disabled_rules:
- line_length
- nesting
- leading_whitespace
- trailing_whitespace
- cyclomatic_complexity
- function_body_length
- function_parameter_count
- orphaned_doc_comment

included:
excluded:
- Pods
- Recody/TestGroup
- Recody/AppDelegate.swift
- Recody/SceneDelegate.swift
